spring.application.name=real-time-chat
spring.config.import=optional:file:.env[.properties]


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080


app.upload.dir=uploads

50 MB = 52428800 bytes
Keep this in sync with spring.servlet.multipart.max-file-size

app.upload.max-bytes=52428800

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=51MB

app.webrtc.turn-urls=turn:turn.example.com:3478,turns:turn.example.com:5349

app.webrtc.stun-urls=stun:stun.l.google.com:19302
app.webrtc.turn-urls=${TURN_URLS:}
app.webrtc.turn-username=${TURN_USERNAME:}
app.webrtc.turn-credential=${TURN_CREDENTIAL:}



jwt.secret=${JWT_SECRET:change-this-to-a-long-random-base64-secret-change-this-to-a-long-random-base64-secret}
jwt.expiration=${JWT_EXPIRATION:86400000}